# Generated by Django 4.1.4 on 2023-01-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_offer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aluminium_Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("price", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Wood_Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("price", models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name="Price",
            new_name="MPlast_Price",
        ),
    ]
