# Generated by Django 4.1.4 on 2023-01-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0003_aluminium_price_wood_price_rename_price_mplast_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="archive",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
