# Generated by Django 4.1.4 on 2023-01-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0005_rename_image_archive_image_1_archive_image_2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="archive",
            name="name",
            field=models.CharField(default="---", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="archive",
            name="description",
            field=models.TextField(),
        ),
    ]
