# Generated by Django 4.1.4 on 2023-01-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0007_aboutcompany_aboutowner_aboutstaff_delete_about"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutstaff",
            name="name",
            field=models.CharField(default="---", max_length=60),
            preserve_default=False,
        ),
    ]
