# Generated by Django 4.0.6 on 2023-02-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_aboutstaff_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='link',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
